### ISSUE TITLE
Missing debugging symbols

### ISSUE THREAD

**Issue by ArturGaspar** [sailfishos-chum/qt5#10]
qtwayland and at least some packages other than qtbase have empty debuginfo and debugsource rpms.

**Comment by rinigus** [comment]
Thanks for reporting. Maybe you could also look into it?

**Comment by rinigus** [comment]
There are general issues with debug symbols and stripping. So, would be good to look into it

**Comment by ArturGaspar** [comment]
Here are all the clues I found to it. No idea where to go from here.

- qtbase.spec passes `QMAKE_STRIP=` to %make_build. I have tried passing the same to %{opt_qmake_qt5} in qtwayland.spec but it did not fix the build.

- Build output vs. rpmlint output:

```
WARNING: /opt/qt5/lib64/libQt5WaylandClient.so.5.15.8 is already stripped!
WARNING: /opt/qt5/lib64/libQt5WaylandCompositor.so.5.15.8 is already stripped!
...
```
```
opt-qt5-qtwayland.aarch64: W: unstripped-binary-or-object /opt/qt5/lib64/libQt5WaylandClient.so.5.15.8
opt-qt5-qtwayland.aarch64: W: unstripped-binary-or-object /opt/qt5/lib64/libQt5WaylandCompositor.so.5.15.8
...
```

**Comment by rinigus** [comment]
Yes, have seen those as well. Rather confusing

**Comment by rinigus** [comment]
I think it is solved now with the updated macro %opt_qmake_qt5: https://github.com/sailfishos-chum/qt5/blob/main/macros.qt5#L34

Closing. Please reopen if it is still a problem after testing with the new libs (expect them being ready tomorrow, as I am working on dependencies)
